### PR TITLE
laplan install fix in Dockerfile

### LINKED ISSUE #50: "setup.py" not found for laplan
Running into this error during `docker-compose build` after #46 :

```
Step 5/5 : RUN pip install -r /tmp/requirements.txt
 ---> Running in 4fb999c7d01e
ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: /root/work
ERROR: Service 'lab' failed to build: The command '/bin/sh -c pip install -r /tmp/requirements.txt' returned a non-zero code: 1
```

Managed to fix it by copying over laplan with two lines in Dockerfile before the pip install since the `requirements.txt` is having pip install with option -e for local package installation.  It didn't see it in WORKDIR /root/work in the container it was setting up for the `lab` service in docker-compose using the `citywide-civis-lab:497b06e9b88f ` image.  Let me know if it's an issue on my end.

```
COPY laplan ./laplan
COPY setup.py .

RUN pip install -r /tmp/requirements.txt
```

### PR DESCRIPTION
**Pull request by trantom**
Specify copy of `setup.py` and  `laplan` over to working directory in container for install.  Minor fix on `pip install requirements.txt` on `README.md` for missing option `-r`.  This is to fix issue #50.

### CODE REVIEW

**Comment by ian-r-rose** [comment]
Just had a thought about a drawback of this approach. If the user wants to develop the `laplan` package while in the docker image, changes won't be reflected in their running python process (because this makes a copy of the package and pip installs it).

What if, instead of copying it into the container, we add the pip install as part of the docker-compose command? Then we could do an editable install and allow the user to develop with the package.

**Comment by ian-r-rose** [comment]
That is to say, we could go to this line:
https://github.com/CityOfLosAngeles/planning-entitlements/blob/a2ef89d4853baf0f9121cc0dc0cfe2db9ed341d8/docker-compose.yml#L18
and prepend the command with `pip install -e /app &&`
and do the same with this line: https://github.com/CityOfLosAngeles/planning-entitlements/blob/a2ef89d4853baf0f9121cc0dc0cfe2db9ed341d8/docker-compose.yml#L29

**Comment by trantom** [comment]
@ian-r-rose You make a good point.  I've prepended as you have suggested, but I had to do it in the exec form for it to run 
successfully instead of shell form even though there is the underlying `/bin/sh/ -c` already.  

```
command: ["/bin/sh","-c","pip install -e /app && jupyter-lab --no-browser --ip=\"*\" --allow-root --port=8888 --NotebookApp.notebook_dir=/app --NotebookApp.terminado_settings='{\"shell_command\": [\"bash\"]}' --LabApp.token=\"\" --LabApp.password=\"\""]
```

Otherwise in shell form it gives me the error:

```
planning-entitlements | Usage:
planning-entitlements |   pip install [options] <requirement specifier> [package-index-options] ...
planning-entitlements |   pip install [options] -r <requirements file> [package-index-options] ...
planning-entitlements |   pip install [options] [-e] <vcs project url> ...
planning-entitlements |   pip install [options] [-e] <local project path> ...
planning-entitlements |   pip install [options] <archive url/path> ...
planning-entitlements |
planning-entitlements | no such option: --no-browser
```

Lastly, we would need to remove `-e .` from `requirements.txt` or remove the last two lines of `COPY` and `pip install` from the Dockerfile as some potential options to not have `docker-compose build` fail.  Removing the lines from the Dockerfile will still enable `pip install -r requirements.txt` while removing the `-e .` from `requirements.txt` will leave an empty file and two commands in the Dockerfile that would not do anything leaving a sort of blank template if future libraries are to be installed through `requirements.txt`.  What would you suggest?

**Comment by ian-r-rose** [comment]
> 
> 
> @ian-r-rose You make a good point. I've prepended as you have suggested, but I had to do it in the exec form for it to run
> successfully instead of shell form even though there is the underlying `/bin/sh/ -c` already.
> 
> ```
> command: ["/bin/sh","-c","pip install -e /app && jupyter-lab --no-browser --ip=\"*\" --allow-root --port=8888 --NotebookApp.notebook_dir=/app --NotebookApp.terminado_settings='{\"shell_command\": [\"bash\"]}' --LabApp.token=\"\" --LabApp.password=\"\""]
> ```
Huh, I confess I'm not sure why we need to use command form here, but others seem to have found the [same issue](https://stackoverflow.com/questions/30063907/using-docker-compose-how-to-execute-multiple-commands). I have no objection to doing that here.

> 
> Lastly, we would need to remove `-e .` from `requirements.txt` or remove the last two lines of `COPY` and `pip install` from the Dockerfile as some potential options to not have `docker-compose build` fail. Removing the lines from the Dockerfile will still enable `pip install -r requirements.txt` while removing the `-e .` from `requirements.txt` will leave an empty file and two commands in the Dockerfile that would not do anything leaving a sort of blank template if future libraries are to be installed through `requirements.txt`. What would you suggest?

I think it's fine to have a minimal/empty dockerfile here.

**Comment by trantom** [comment]
@ian-r-rose Thank you for all of the feedback and suggestions.  I've modified the files in the new commit and it is ready for review and merging if acceptable.

**Comment by ian-r-rose** [comment]
Thanks for identifying the issue and making the fix @trantom!

**Comment by trantom** [comment]
@ian-r-rose No problem.  I appreciate all of the feedback and guidance!

**Pull request merged**
